# Generated by Django 5.2.7 on 2025-11-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='collection',
            new_name='item_collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_items',
            field=models.ManyToManyField(blank=True, related_name='collections', to='collections_app.item'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
