# Generated by Django 5.2.7 on 2025-11-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_rename_collection_item_item_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
