# Generated by Django 5.2.7 on 2025-11-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0003_collection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_items',
        ),
    ]
